# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy

gomod:
  proxy: true

builds:
- env: ["CGO_ENABLED=0"]
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags: ["-trimpath"]
  ldflags: ["-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }}"]
  targets: ["go_first_class"]

dockers:
  - image_templates:
    # Docker Hub (amd64)
    - "victorbersy/docker-hub-cli:latest-amd64"
    - "victorbersy/docker-hub-cli:{{ .Tag }}-amd64"
    - "victorbersy/docker-hub-cli:v{{ .Major }}.{{ .Minor }}-amd64"
    - "victorbersy/docker-hub-cli:v{{ .Major }}-amd64"
    # Github (amd64)
    - "ghcr.io/victorbersy/docker-hub-cli:latest-amd64"
    - "ghcr.io/victorbersy/docker-hub-cli:{{ .Tag }}-amd64"
    - "ghcr.io/victorbersy/docker-hub-cli:v{{ .Major }}.{{ .Minor }}-amd64"
    - "ghcr.io/victorbersy/docker-hub-cli:v{{ .Major }}-amd64"
    dockerfile: Dockerfile.goreleaser
    use: buildx
  - image_templates:
    # Docker Hub (arm64)
    - "victorbersy/docker-hub-cli:latest-arm64"
    - "victorbersy/docker-hub-cli:{{ .Tag }}-arm64"
    - "victorbersy/docker-hub-cli:v{{ .Major }}.{{ .Minor }}-arm64"
    - "victorbersy/docker-hub-cli:v{{ .Major }}-arm64"
    # Github (arm64)
    - "ghcr.io/victorbersy/docker-hub-cli:latest-arm64"
    - "ghcr.io/victorbersy/docker-hub-cli:{{ .Tag }}-arm64"
    - "ghcr.io/victorbersy/docker-hub-cli:v{{ .Major }}.{{ .Minor }}-arm64"
    - "ghcr.io/victorbersy/docker-hub-cli:v{{ .Major }}-arm64"
    dockerfile: Dockerfile.goreleaser
    use: buildx

docker_manifests:
- name_template: victorbersy/docker-hub-cli:{{ .Version }}
  image_templates:
  # Docker Hub (amd64)
  - "victorbersy/docker-hub-cli:latest-amd64"
  - "victorbersy/docker-hub-cli:{{ .Tag }}-amd64"
  - "victorbersy/docker-hub-cli:v{{ .Major }}.{{ .Minor }}-amd64"
  - "victorbersy/docker-hub-cli:v{{ .Major }}-amd64"
  # Docker Hub (arm64)
  - "victorbersy/docker-hub-cli:latest-arm64"
  - "victorbersy/docker-hub-cli:{{ .Tag }}-arm64"
  - "victorbersy/docker-hub-cli:v{{ .Major }}.{{ .Minor }}-arm64"
  - "victorbersy/docker-hub-cli:v{{ .Major }}-arm64"
- name_template: ghcr.io/victorbersy/docker-hub-cli:{{ .Version }}
  image_templates:
  # Github (amd64)
  - "ghcr.io/victorbersy/docker-hub-cli:latest-amd64"
  - "ghcr.io/victorbersy/docker-hub-cli:{{ .Tag }}-amd64"
  - "ghcr.io/victorbersy/docker-hub-cli:v{{ .Major }}.{{ .Minor }}-amd64"
  - "ghcr.io/victorbersy/docker-hub-cli:v{{ .Major }}-amd64"
  # Github (arm64)
  - "ghcr.io/victorbersy/docker-hub-cli:latest-arm64"
  - "ghcr.io/victorbersy/docker-hub-cli:{{ .Tag }}-arm64"
  - "ghcr.io/victorbersy/docker-hub-cli:v{{ .Major }}.{{ .Minor }}-arm64"
  - "ghcr.io/victorbersy/docker-hub-cli:v{{ .Major }}-arm64"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^chore'
    - Merge pull request
    - Merge remote-tracking branch
    - Merge branch
    - go mod tidy
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 999

release:
  footer: |

    ---

    _Released with [GoReleaser](https://goreleaser.com)!_
