name: golangci-lint
on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v5
        with:
          go-version: ~1.20
          cache: true
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          skip-go-installation: true
